name: acidghost's github page!
pygments: true
github: {
    "versions": {
      "jekyll": "1.5.1"
    },
    "hostname": "github.io",
    "pages_hostname": "github.io",
    "environment": "dotcom",
    "public_repositories": "https://api.github.com/users/acidghost/repos",
    "owner_name": "acidghost",
    "owner_url": "https://github.com/acidghost",
    "owner_gravatar_url": "https://github.com/acidghost.png",
    "repository_url": "https://github.com/acidghost/acidghost.github.io",
    "repository_nwo": "acidghost/acidghost.github.io",
    "repository_name": "acidghost.github.io",
    "zip_url": "https://github.com/acidghost/acidghost.github.io/zipball/",
    "tar_url": "https://github.com/acidghost/acidghost.github.io/tarball/",
    "clone_url": "https://github.com/acidghost/acidghost.github.io.git",
    "releases_url": "https://github.com/acidghost/acidghost.github.io/releases",
    "issues_url": "https://github.com/acidghost/acidghost.github.io/issues",
    "wiki_url": "https://github.com/acidghost/acidghost.github.io/wiki",
    "language": null,
    "is_user_page": true,
    "is_project_page": false,
    "show_downloads": true,
    "url": "http://acidghost.github.io/", // (or the CNAME)
}
#source: ./_source
